spring:
 security:
   oauth2:
     client:
       registration:
         okta:
           client-id: 0oaf66ynklXcUzRbx0h7
           client-secret: aU5zwROBbRVmJfDDRUerdEeq5V0R6UtZmt9BRDCM
       provider:
         okta:
           authorization-uri: https://dev-803902.oktapreview.com/oauth2/default/v1/authorize
           token-uri: https://dev-803902.oktapreview.com/oauth2/default/v1/token
           user-info-uri: https://dev-803902.oktapreview.com/oauth2/default/v1/userinfo
           jwk-set-uri: https://dev-803902.oktapreview.com/oauth2/default/v1/keys
